"""Add email and alert_message columns to Token

Revision ID: 19b41ba38d48
Revises: 7fd4eea37f58
Create Date: 2025-07-28 15:08:00.265003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b41ba38d48'
down_revision = '7fd4eea37f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('alert_message', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_column('alert_message')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
